# fly.toml file generated for prismaexpress on 2023-04-18T08:24:06-03:00

app = "prismaexpress"
primary_region = "gig"

[http_service]
  internal_port = 3000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
