# fly.toml file generated for prismaexpress on 2023-09-29T17:54:36-03:00

app = "prismaexpress"
primary_region = "gru"

[http_service]
internal_port = 3000
force_https = true

[checks]
[checks.alive]
type = "tcp"
interval = "15s"
timeout = "2s"
grace_period = "5s"


