name: Fly Deploy
on:
    workflow_run:
        workflows:
        - Prisma Migrate
        types:
        - completed
    push:
     branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: teste
    steps:
      - uses: actions/checkout@v3
      - run: npx prisma migrate deploy
      - run: echo "Deploying to Fly.io $vars.DATABASE_URL"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}